println("Etapa 1/5 :")
run(`julia video_to_frames.jl`)
println("Etapa 2/5 :")
run(`julia --threads 8 frames_to_temporal.jl`)
println("Etapa 3/5 :")
run(`julia svd.jl`)
println("Etapa 4/5 :")
run(`julia svd_to_foreground.jl`)
println("Etapa 5/5 :")
run(`julia frames_to_video.jl`)
println("Finalizado!")
